### PR TITLE
Bug fix for arcAngle. Changed getDimension to getFloat

### PR DESCRIPTION
**Pull request by vivekm26**
Bug fix for arcAngle.

### CODE REVIEW

**Comment by vivekm26** [comment]
Thank you so much

**Comment by vivekm26** [comment]
I will be really helpful if you can release this version in jcenter. Thanks again.

**Comment by lzyzsd** [comment]
@vivekm26 I will publish a new version to jcenter tonight

**Comment by vivekm26** [comment]
Awesome Thanks !!

**Comment by lzyzsd** [comment]
@vivekm26 I have made to publish request to jcenter

**Pull request merged**
