### PR TITLE
Added Float ArcProgress

### PR DESCRIPTION
**Pull request by hoseinit**
hi @lzyzsd 
Please tell me How I can manage to have both Progress for Integers and Floats.
Thnaks

### CODE REVIEW

**Comment by sandysultan** [comment]
now the number always have decimal, how to remove it?

**Comment by jiao808813** [comment]
how to remove .0 ?

**Comment by billrancho** [comment]
how to remove , .0 then, I dont want to override

**Comment by KhaledLela** [comment]
@billrancho Please checkout my PR #103

**Pull request merged**
